const portafolio = [
  { Titulo : 'NaxChatApp',img : '/images/App/1.jpg',parrafo : 'Chat multiplataforma, puedes mandar gifs, fotos, solicitudes de amistad, notificaciones push en 2do plano y más. <br><br> Quasar VueJs Vuex Firebase NodeJs Android Capacitor Cordova',links : [{ name: 'App', link: 'https://asdf-3e590.web.app' },{ name: 'Github', link: 'https://github.com/naxo25/App-Chat-Quasar-VueJs-Firebase' },{ name: 'download', link: 'https://github.com/naxo25/NaxChatApp/blob/main/dist/Android/' }],icos : [ 'vue2', 'nodeJs', 'firebase', 'ionic', 'cordova', 'quasar' ]},
  { Titulo : 'Smart-TV Estadio TNT Sports',img : '/images/App/logo-tv.jpg',parrafo : 'Aplicación Smart-TV de fútbol para televisores. <br><br> WebOS LG Tizen Samsung VueJs Vuex Firebase NodeJs',links : [{ name: 'App', link: 'https://cl.estadio.com/' }],icos : [ 'vue2', 'nodeJs', 'firebase', 'ionic', 'cordova', 'quasar' ]},
  { Titulo : 'Concurso para sorteo Auto',img : '/images/App/auto.png',parrafo : 'Web que hice para la inscripción y canjeo de cupones de los participantes para el sorteo de un auto. <br><br> Quasar VueJs Firebase Wordpress',links : [{ name:'Portafolio', link:'https://agg7765473-286bb.web.app' }],icos : [ 'vue2', 'firebase', 'quasar' ]},
  { Titulo : 'App CFGym',img : '/images/App/2.png',parrafo : 'Aplicación para llevar el registro de socios, pagos, planes entre otras actividades de un gimnasio. <br><br> Quasar Firebase',links : [{ name: 'Demo', link: 'https://nacholabraweb.000webhostapp.com/pwa/EjApp/#/Clientes' }],icos : [ 'js', 'vueJs', 'nodeJs' ]},
  { Titulo : 'Comercial Vas',img : '/images/App/6.png',parrafo : 'Aplicación para manejar stock en bodegas, hecha en mi práctica. <br><br> Jquery Php Boostrap Html Javascript',links : [{ name: 'Demo', link: 'https://nacholabraweb.000webhostapp.com/Crud/' },{ name: 'Github', link: 'https://github.com/naxo25/php7' }],icos : [ 'jquery', 'css', 'js', 'php', 'bootstrap' ]},
  { Titulo : 'Trabajo de título UTFSM',img : '/images/App/5.jpg',parrafo : 'VideoJuego Rpg hecho con librería pygame. <br><br> Python',links : [{ name: 'VideoDemo', link: 'https://drive.google.com/file/d/1uzLFazwiEtSXMGWIAdsnqirCwrY0KnDG/view' },{ name: 'Github', link: 'https://github.com/naxo25/Python' }],icos : [ 'python' ]}
];

const desc_presentacion = [
  'Informático frontend web y smart tv. Estoy en contanste búsqueda de qué aprender, como mejorar mi forma de programar, mi logica y el rendimiento de las aplicaciones, siempre estoy viendo que y como puedo mejorar.',
  `He hecho aplicaciones usando principalmente en el front VueJs e integraciones backend usando Firebase y Supabase, tambíen he hecho aplicaciones móviles con cordoba y capacitor, pwa, electron.<br><br> Contactamé y dime como puedo ayudarte. <br><br> <a style='text-decoration: none; color: var(--vue); font-weight: bolder' href="https://github.com/naxo25" target="blank"> Github</a>`
];

const icons = [/*{ ico: 'linkedin.svg', href: 'https://www.linkedin.com/in/ignacio-labra-54bab9177' },*/{ ico: 'gmail.png', href: 'mailto:naxorojas25@gmail.com' },{ ico: 'naxchat.png', href: 'https://asdf-3e590.web.app' },{ ico: 'github.png', href: 'https://github.com/naxo25' },{ ico: 'youtube.svg', href: 'https://www.youtube.com/channel/UClJr019QbaWJy3klKDOenXQ' }];

const header = [{ to: '#', name: 'Inicio' },{ to: '#About', name: 'Acerca' },{ to: '#Portafolio', name: 'Portafolio' },{ to: 'https://nacholabraweb.000webhostapp.com/naxtasksApp', name: 'NaxtasksApp' },{ to: 'https://nacholabraweb.000webhostapp.com/Tutoriales/dist', name: 'Tutoriales' },{ to: '#Redes', name: 'Naxchat y redes' }];